### ISSUE TITLE
edits not appearing in repo

### ISSUE THREAD

**Issue by hackettka** [DHRI-Curriculum/html-css#10]
@smythp i'm making my edits to the curriculum html/css repo now, and when i refresh the page, i'm not seeing the edits. Is this because you need to review and accept them (according to github)? I just want to make sure I'm doing this correctly.

**Comment by smythp** [comment]
Hi Kristen, did you manage to push your changes? Looks like you have push access now.

**Comment by hackettka** [comment]
Yes i was able to do that - thanks for following up!
