### ISSUE TITLE
In opening, are do all browsers have View Source?

### ISSUE THREAD

**Issue by smythp** [DHRI-Curriculum/html-css#2]

**Comment by hackettka** [comment]
check chrome, safari, firefox..

**Comment by hackettka** [comment]
@smythp I don't see any way to 'view page source' or 'inspect element' in safari.. 

In firefox and chrome it is 'View Page Source'

**Comment by smythp** [comment]
There's a way to get it working, but it's probably not worth 
listing how. (It's like 5 steps.) Maybe just make a note for 
Safari users to grab Firefox.

**Comment by hackettka** [comment]
ive added some text to the opening activity. let me know if you think it needs more. thanks!
