### ISSUE TITLE
In opening activity, text to tell how to right click without a mouse

### ISSUE THREAD

**Issue by smythp** [DHRI-Curriculum/html-css#3]
Yes, OSX users need to be told this every time. :(

**Comment by hackettka** [comment]
"open secondary menu"  -- usually a right click.. 

control button and click always works.

**Comment by smythp** [comment]
Say that they can hold the Control button and click to activate secondary menu.

**Comment by smythp** [comment]
Looks like Kelsey made this change. Closing.
