### ISSUE TITLE
Resources page

### ISSUE THREAD

**Issue by kchatlosh** [DHRI-Curriculum/html-css#31]
Just a reminder to add a resources page 

Also, to include on that page, Hannah suggested this guide to HTML on Mozilla:
https://developer.mozilla.org/en-US/docs/Web/HTML

There's also another guide to CSS on Mozilla:
https://developer.mozilla.org/en-US/docs/Web/CSS

It would be good if you / someone could also find a source that discusses universal design or design for folks for physical disabilities that addresses HTML and/or CSS

**Comment by hackettka** [comment]
thanks for this kelsey! we're on the same wavelength :)
