### ISSUE TITLE
"Making your website public" section of the lesson needs to be revised

### ISSUE THREAD

**Issue by paramajmera** [DHRI-Curriculum/html-css#48]
The current "making your website public" section doesn't provide enough concrete information on how to actually put a website on the internet. It abstractly discusses FTP and web hosting, without providing step-by-step instructions to make a website public. Some suggestions / thoughts on improving this section:

1. Include more information on content management systems like wordpress, scalar, and omeka. This can be a way of learning-by-doing, and it can give people confidence in putting up a website.
2. Include a robust overview of reclaim hosting. This can teach people how to buy a domain name and use a virtual server.
3. Include an assignment on using StoryMaps. This can help bring together the lessons on GIS and website development.

**Comment by kallewesterling** [comment]
@hackettka Was this what you were referring to as the "Introduction to platforms" workshop..?

**Comment by hackettka** [comment]
Not exactly. At the DRI I did a separate workshop - see here: https://docs.google.com/presentation/d/11ZSjt7p3mJ6ruRviwWy62FiLoAwS0rgiTvnuqZYYwMs/edit?usp=sharing

**Comment by kallewesterling** [comment]
Closing this as #52 is where we're currently discussing this content
