### ISSUE TITLE
Frontmatter 

### ISSUE THREAD

**Issue by smorello87** [DHRI-Curriculum/html-css#53]
I wonder if it makes sense to mention Wordpress somewhere in the frontmatter file. It's my understanding that it would help folks connect the kind of work done in the workshop with a platform that they might be familiar with. If so, I think it would make sense to have it either in the opening blurb or in the "Projects that use these skills" section.

Also, in Ethical considerations, we may want to add a link  to thee WAVE Tool https://wave.webaim.org/ so folks can see firsthand what an accessible website entails (and how many high profile websites that seem to be accessible, are not THAT accessible!). Maybe also explain what screen readers are?

**Comment by kallewesterling** [comment]
The WAVE Tool is so great - I didn't know about it until now!
