### ISSUE TITLE
Lessons

### ISSUE THREAD

**Issue by smorello87** [DHRI-Curriculum/html-css#56]
Ok, last issue for today. 

1) In the opening activity, where we show folks how to access a webpage source – is there any way to do this with [I.E.](https://www.lifewire.com/view-html-source-in-explorer-3464080) or [Edge](http://webitblog.com/2015/11/view-the-source-code-of-a-web-page/)? 

 2) I think it makes sense to explain what XML and XHTML are, or at least add a link to them? Again, this is one of those things we would just mention in passing in an in person workshop, and we may need to be super-specific and more careful in spelling things out in this new format. 

3) I wonder if it makes more sense to break down those challenges into smaller/scaffolding ones + add solutions (maybe in the form of a screenshot AND either a txt file with the code or embedding the code in the page?)

4) The "Additional Tags" subsection shouldn't be a subsection of a challenge, according to the templates. Correct? @kallewesterling

**Comment by kallewesterling** [comment]
As for (4), you can certainly have a subsection inside the challenge if you want - it should work in the ingestion process, I believe.. but if it's a different section, then the challenge should go last, before the next level 1 heading (`#`).

**Comment by kallewesterling** [comment]
I also looked up the 80% number that we refer to, and crazily enough, it's up to 90% now: https://w3techs.com/technologies/overview/markup_language
