### ISSUE TITLE
Central markdown files finalized

### ISSUE THREAD

**Issue by kallewesterling** [DHRI-Curriculum/html-css#58]
### `lessons.md`

- [x] Accept any [pending pull requests](../pulls)

- [x] Implement all the edits/requests that you have left from your colleagues ([Di's comments](https://github.com/DHRI-Curriculum/html-css/issues/52), and Stefano's comments on [lessons](https://github.com/DHRI-Curriculum/html-css/issues/56), [theory-to-practice](https://github.com/DHRI-Curriculum/html-css/issues/55), [assessment](https://github.com/DHRI-Curriculum/html-css/issues/54), and [frontmatter](https://github.com/DHRI-Curriculum/html-css/issues/53))

- [x] Add any additional content you think is needed for version 2.0 _and open any other using the [![](https://img.shields.io/github/labels/dhri-curriculum/data-literacies/wishlist)](../labels/wishlist) label in your repo

- [x] Ensure the length of each lesson is not too long
    _each section (beginning with a level 1 heading [#]) should be no more than 3-4 paragraphs_

- [x] Ensure temporal references and references to other workshops are removed (since learners will “attend” these workshops mostly asynchronously)

### `frontmatter.md`

- [x] Finalize and streamline all sections

- [x] Ensure your abstract is no longer than ~100 words
   _If you need/want them to be longer, you can create a new first section in lessons.md and put the longer version of the abstract there._

- [x] Resolve any "TBD" content.

- [x] Make sure collaborator lists are complete with roles and links
   _see [Di’s example](https://github.com/DHRI-Curriculum/html-css/blob/v2.0-di-edits/frontmatter.md#acknowledgements) but feel free to add links to people’s websites!_

- [x] Ensure all Projects and Readings have "annotations"
   _annotations = 1-2 sentences answering “Why is it important for our learners to read or expose themselves to these readings/projects”? For examples, see [agenda doc](https://docs.google.com/document/d/18MImAjxv3_cYKuGvnvsLS0L8Dkn8jSluMxOjeWv2G8k/edit#)_

### `theory-to-practice.md`

- [x] Finalize and streamline all sections

- [x] Resolve any "TBD" content.

- [x] Ensure all Projects, Readings, and Tutorials have "annotations"
   _annotations = 1-2 sentences answering “Why is it important for our learners to read or expose themselves to these readings/projects”? For examples, see [agenda doc](https://docs.google.com/document/d/18MImAjxv3_cYKuGvnvsLS0L8Dkn8jSluMxOjeWv2G8k/edit#)_

**Comment by paramajmera** [comment]
Hey @kallewesterling ! I just wanted to get a clarification on the task of removing references to other workshops. My workshop uses command line concepts like navigating the file tree as well as creating files and folders. Furthermore my workshop clearly discusses how to perform these tasks. Should I keep these references to the command line? If the HTML workshop is released after the command line workshop, then it would be nice to review these concepts. Do you know if we are still planning on releasing one workshop per month?

Alternatively, I can remove all references to the command line and discuss ways of creating the files using VS code. Please let me know how to proceed. 

Thanks!

**Comment by kallewesterling** [comment]
We are planning to release one workshop per month going forward, yes.

I don't think we need references to the Command Line workshop every time that we run a command on the command line. Rather, I think that it might be good to put the Command Line workshop as a good prerequisite for this workshop, if it is using a lot of commands run through a CLI throughout. You might want to add a bullet point in the `## Prerequisites` heading in `frontmatter.md` with a note about the command line being used throughout the workshop and therefore, while the commands should be clear and fairly easy to grasp, it might be good for someone who is taking this workshop asynchronously (and potentially without the help of fellows!) to first go through the Command Line workshop.

**Comment by paramajmera** [comment]
Thanks for the clarification! I will add command line to the prerequisites.

**Comment by kallewesterling** [comment]
Since we're now in `sprint 5` I will go ahead and close this issue. Feel free to re-open if you think we have unresolved issues in this item.
