### ISSUE TITLE
In images, are images critical for communicating information to visitors?

### ISSUE THREAD

**Issue by smythp** [DHRI-Curriculum/html-css#7]
Unfortunately, they often are, but, at least according to universal design principles, they shouldn't be. If images are conveying crucial information, then the site isn't accessible.

**Comment by hackettka** [comment]
good point- will adjust!

**Comment by hackettka** [comment]
i think we should add an alt text attribute to this section too. this is CSS right? 

<img src="smiley.gif" alt="Smiley face">

**Comment by smythp** [comment]
Yes, thank you. I appreciate the VI pandering :)

**Comment by smythp** [comment]
Sorry, closed by accident.

**Comment by kchatlosh** [comment]
Hi all -- just to add to this, it would be good to also add that it is a requirement in HTML to add a text description for every image, and also show the code for how to do that in the "images" section of this workshop (I'm thinking back to that time I tweeted about your workshop and got a hard time about this)

**Comment by hackettka** [comment]
same wavelength again kels!
